global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'nextjs-app'
    metrics_path: /api/metrics
    static_configs:
      - targets: ['app:3000']

  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka:7071']
